<?php

namespace Tests\Feature;

use App\Models\Post;
use App\Models\Team;
use App\Models\User;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;



class LikTest extends TestCase
{


    use DatabaseTransactions;


    /**
     * @var \Illuminate\Database\Eloquent\Collection|\Illuminate\Database\Eloquent\Model
     */
    protected $post;
    protected $user;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->post = Post::factory()->create();
        $this->signIn();
    }

    /**
     * @test
     */
    public function a_user_can_like_a_post()
    {

        
        $this->post->like();

        $this->assertDatabaseHas(
           'likes', [
                'user_id'       => $this->user->id,
                'likeable_id'   => $this->post->id,
                'likeable_type' => get_class($this->post)
            ]
        );

        $this->assertTrue($this->post->isLiked());
    }


    /**
     * @test
     */
    public function a_user_can_unlike_a_post()
    {





        $this->post->like();
        $this->post->unlike();

        $this->assertDatabaseMissing(
            'likes', [
                'user_id'       => $this->user->id,
                'likeable_id'   => $this->post->id,
                'likeable_type' => get_class($this->post)
            ]
        );

        $this->assertFalse($this->post->isLiked());
    }


    /**
     * @test
     */
    public function a_user_can_toggle_like_a_post()
    {




        $this->post->toggle();
        $this->assertTrue($this->post->isLiked());

        $this->post->toggle();
        $this->assertFalse($this->post->isLiked());

    }

    /**
     * @test
     */
    public function a_post_know_how_many_likes_it_has()
    {




        $this->post->toggle();

        $this->assertEquals(1, $this->post->likesCount);


    }


}
